universe = docker
docker_image = pytorch/pytorch:2.1.0-cuda12.1-cudnn8-devel
executable = run_task.sh
arguments = /home/hepe00001/readout_guidance/demo_drag.py
environment = PROJECT_ROOT=$ENV(PWD)
initialdir  = $ENV(PWD)
output = logs/output.out
error  = logs/error.err
log = logs/log.log
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
request_GPUs = 1
request_CPUs = 1
request_memory = 32G
getenv                  = HOME
+WantGPUHomeMounted     = true
queue

